version: '2'

services:
  influxdb:
    image: influxdb:1.2
    ports:
      - "8083:8083"
      - "8086:8086"
      - "35826:25826/udp"
    volumes:
      - ./influxdb:/var/lib/influxdb:Z
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:Z
      - ./types.db:/usr/share/collectd/types.db:Z
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana:Z
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
      - "-storage.remote.influxdb-url=http://influxdb:8086/"
      - "-storage.remote.influxdb.database=prometheus"
  exporter:
    image: prom/collectd-exporter
    ports:
      - "9103:9103"
      - "25826:25826/udp"
    command:
      - "-collectd.listen-address=:25826"
